// Generated by CoffeeScript 1.8.0

/*
	Copyright (c) Prithvi Kohli 2014
	All rights reserved
	prithvikohli.co.uk
	Contact: prithvi@prithvikohli.co.uk
 */

(function() {
  var HEIGHT, WIDTH, arrow, c, ctx, game, logo_fall, logo_rock, requestAnimationFrame;

  c = $('#game')[0];

  ctx = c.getContext('2d');

  WIDTH = window.innerWidth;

  HEIGHT = window.innerHeight;

  requestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

  logo_rock = new Image();

  logo_fall = new Image();

  arrow = new Image();

  game = {
    main_hasStarted: false,
    preload: function() {
      logo_rock.src = 'assets/images/Logo-rock.png';
      logo_rock.onload = function() {
        return console.log('LOGO_ROCK LOADED');
      };
      logo_fall.src = 'assets/images/Logo-fall.png';
      logo_fall.onload = function() {
        return console.log('LOGO_FALL LOADED');
      };
      game.init();
    },
    init: function() {
      c.width = 500;
      c.height = 500;
      if (HEIGHT > WIDTH) {
        alert('Game best played in landscape orientation!');
      }
      game.render();
    },
    render: function() {
      ctx.clearRect(0, 0, 500, 500);
      if (game.main_hasStarted === false) {
        game.menu.renderMenu();
      }
      requestAnimationFrame(game.render);
    },
    menu: {
      intro: {
        fall_hasFinished: false,
        shake_hasFinished: false,
        rock_posY: -100,
        fall_posY: -100,
        rock_posX: 146,
        fall_posX: 146,
        shake_direction: 'down',
        shake_fact: 10
      },
      renderMenu: function() {
        ctx.drawImage(logo_rock, game.menu.intro.rock_posX, game.menu.intro.rock_posY);
        ctx.drawImage(logo_fall, game.menu.intro.fall_posX, game.menu.intro.fall_posY);
        if (game.menu.intro.fall_hasFinished === false) {
          if (game.menu.intro.rock_posY < 100) {
            return game.menu.intro.rock_posY++;
          }
        } else {
          if (game.menu.intro.fall_posY < 171) {
            game.menu.intro.fall_posY += 4.5;
            return game.audio.playOnce('logo-fall');
          } else {
            game.audio.playOnce('logo-hit');
            game.menu.intro.fall_hasFinished = true;
          }
        }
      }
    },
    audio: {
      old: null,
      playOnce: function(sound) {
        if (sound !== game.audio.old) {
          $('#' + sound)[0].play();
          game.audio.old = sound;
        }
      }
    }
  };

  $(game.preload());

}).call(this);
